let titleBook = prompt("Tên sách :");
let authorBook = prompt("Tên tác giả :");
let yearPublication = prompt("Năm xuất bản :");
let valueBook = prompt("Giá tiền :");
let quantityBook = prompt("Số lượng :");
let titleBookAccess = titleBook.trim().toUpperCase();
let authorBookAccess = authorBook.toUpperCase();
let firstName = authorBook.substring(0, 3);
let randomNumber = Math.floor(Math.random()*1000)+1;
let bookID = `LIB - ${firstName}${yearPublication} - ${randomNumber}`;
let newYearBook = prompt("Nhập năm hiện tại:");
let randomer = Math.floor(Math.random()*10)+1;
YearBook = newYearBook - yearPublication;
totalInventory = valueBook * quantityBook;
console.log("--- PHIẾU NHẬP KHO ---");
console.log("Mã sách:" + " " + bookID);
console.log("Tên sách:" + " " + titleBookAccess);
console.log("Tác giả:"+ " " + authorBookAccess);
console.log("Năm xuất bản:"+ " " + yearPublication);
console.log("Tuổi của sách:"+ " " + YearBook);
console.log("Tổng giá trị:"+ " " + totalInventory);
console.log("Ngăn sách gợi ý:"+ " " + randomer);